version: "3"
networks:
  mysql-network:
services: 
  covid_app:
    image: kr/covid_whitney 
    container_name: covid_whitney
    restart: always
    build: .
    depends_on:
      - mysql
    ports: 
      - "1337:1337"
    networks:
      - mysql-network
  mysql:
      image: mysql/mysql-server:latest
      container_name: mysql_whitney
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 'root'
      command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
      ports:
        - "3306:3306"
      volumes:
        - /data/covid19/mysql:/var/lib/mysql
        - ./schema:/docker-entrypoint-initdb.d/:ro
      networks:
        - mysql-network
