version: '3'

volumes:
  certbot_etc:

services:
  certbot:
    image: certbot/dns-cloudflare
    volumes:
      - ./data/certbot_etc:/etc/letsencrypt
      - ./runyan.dev:/etc/nginx/nginx.conf
      - ./cloudflare.ini:/root/cloudflare.ini
    command: >-
      certonly --dns-cloudflare
      --dns-cloudflare-credentials /root/cloudflare.ini
      --dns-cloudflare-propagation-seconds 60
      --email runyanjake@gmail.com
      --agree-tos --no-eff-email
      --force-renewal
      -d runyan.dev
      -d *.runyan.dev

