version: "3"

networks:
  prometheus_network:
    driver: bridge
  grafana_grafana_network:
    external: true
  minecraft_minecraft_network:
    external: true

volumes:
  prometheus_data: {}

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_whitney
    restart: always
    networks:
      - grafana_grafana_network
      - minecraft_minecraft_network
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"

