version: "3.3"

services:

  traefik:
    image: "traefik:v2.9"
    container_name: "traefik_whitney"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - "CF_API_EMAIL=CLOUDFLARE@EMAIL.COM"
      - "CF_API_KEY=API_KEY"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "hello_traefik_whitney"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`MYDOMAIN.COM`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
