version: "3.3"

networks:
  traefik-network:

services:

  traefik:
    image: "traefik:v2.9"
    container_name: "traefik_whitney"
    #    restart: always
    networks:
      - traefik-network
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "./traefik-dynamic.toml:/etc/traefik/dynamic/traefik-dynamic.toml"
      - "./acme.json:/acme.json"

  whoami:
    image: "traefik/whoami"
    container_name: "whoami_whitney"
    networks:
      - traefik-network
    labels:
      - traefik.http.routers.whoami.rule=Host(`whoami.whitney.rip`)
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.tls.certresolver=lets-encrypt
      - traefik.http.services.whoami.loadbalancer.server.port=80
      - traefik.port=80
    depends_on:
      - traefik

