version: '3'

services:
  step1-traefik:
    image: traefik:v2.9
    container_name: step1-traefik
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
