version: "3"

networks:
  grafana_network:
    driver: bridge
  prometheus_prometheus_network:
    external: true
  traefik_traefik-network:
    external: true

volumes:
  grafana_data: {}

services:
  grafana:
    image: grafana/grafana
    container_name: grafana_whitney
    restart: always
    networks: 
      - grafana_network
      - prometheus_prometheus_network
      - traefik_traefik-network
    ports:
      - "3000:3000"
    volumes:
      - ./whitney.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.whitney.rip`)"
      - "traefik.http.routers.grafana.entrypoints=web"
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter_whitney
    user: "995:995"
    restart: always
    networks:
      - grafana_network
    pid: host
    command:
      - "--path.rootfs=/host"
    volumes:
      - "/:/host:ro,rslave"

