version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx_whitney
    restart: always
    network_mode: "host"
    logging:
      driver: "json-file"
      options: 
        max-size: "10m"
        max-file: "25"
    volumes:
      - /var/www/html:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sites-enabled:/etc/nginx/sites-enabled
      - /data/certbot:/data/certbot

