version: "3"
services:
  minecraft:
    image: nimmis/spigot
    container_name: minecraft_whitney_1.16
    restart: always
    ports:
      - "25564:25564"
    volumes:
      - /data/minecraft_1.16:/minecraft
      - ./server.properties:/minecraft/server.properties
    environment:
      - EULA=true
      - MC_MAXMEM=2g
      - MC_MINMEM=512m
