version: "3"
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft_whitney_1.17
    restart: always
    ports:
      - "25565:25565"
    volumes:
      - /data/minecraft_1.17:/data
      - ./server.properties:/data/server.properties
    environment:
      - TYPE=SPIGOT
      - EULA=TRUE

