version: "3"

networks:
  minecraft_network:
    driver: bridge

services:
  minecraft_1.16:
    image: nimmis/spigot
    container_name: minecraft_1.16_whitney
    restart: always
    networks:
      - minecraft_network
    ports:
      - "25564:25564"
    volumes:
      - /data/minecraft_1.16:/minecraft
      - ./server_1.16.properties:/minecraft/server.properties
    environment:
      - EULA=true
      - MC_MAXMEM=2g
      - MC_MINMEM=512m
  minecraft_1.17:
    image: itzg/minecraft-server
    container_name: minecraft_1.17_whitney
    restart: always 
    networks:
      - minecraft_network
    ports:
      - "25565:25565"
      - "9225:9225"
    volumes:
      - /data/minecraft_1.17:/data
      - ./server_1.17.properties:/data/server.properties
      - ./minecraft-prometheus-exporter-2.4.2-SNAPSHOT.jar:/minecraft/plugins/minecraft-prometheus-exporter-2.4.2-SNAPSHOT.jar
    environment:
      - TYPE=SPIGOT
      - EULA=TRUE

