version: "3"

networks:
  minecraft_network:
    driver: bridge

services:
  minecraft_1.16:
    image: itzg/minecraft-server:java15
    container_name: minecraft_1.16_whitney
    restart: always 
    networks:
      - minecraft_network
    ports:
      - "25564:25565"
      - "9224:9225"
    volumes:
      - /data/minecraft_1.16:/data
      - ./server_1.16.properties:/data/server.properties
    environment:
      - TYPE=SPIGOT
      - VERSION=1.16.5
      - EULA=TRUE
  minecraft_1.17:
    image: itzg/minecraft-server
    container_name: minecraft_1.17_whitney
    restart: always 
    networks:
      - minecraft_network
    ports:
      - "25565:25565"
      - "9225:9225"
    volumes:
      - /data/minecraft_1.17:/data
      - ./server_1.17.properties:/data/server.properties
    environment:
      - TYPE=SPIGOT
      - EULA=TRUE

