version: "3"

networks:
  minecraft_network:
    driver: bridge
  traefik_traefik-network:
    external: true

services:
  minecraft_creative:
    image: itzg/minecraft-server:latest
    container_name: minecraft_creative_whitney
    restart: always 
    networks:
      - minecraft_network
    ports:
      - "25566:25565"
      - "9226:9225"
    volumes:
      - /data/minecraft_creative:/data
    environment:
      - TYPE=SPIGOT
      - EULA=TRUE
      - SERVER_NAME=minecraft_creative_whitney
      - MODE=creative
      - DIFFICULTY=peaceful
      - OPS=RicecakeSMS
      - ICON=https://i.imgur.com/sqjZGql.png
      - ENABLE_COMMAND_BLOCK=true
      - GENERATE_STRUCTURES=false
      - MOTD="\u00A77Pinnerland Creative Server, powered by \u00A75P\u00A79W\u00A75S\u00A77\!"
      - PVP=false
      - LEVEL_TYPE=FLAT
      - ALLOW_FLIGHT=true

  minecraft_2023:
    image: itzg/minecraft-server:latest
    container_name: minecraft_2023_whitney
    restart: always 
    networks:
      - traefik_traefik-network
      - minecraft_network
    ports:
      - "25565:25565"
      - "9225:9225"
      - "8123:8123"
    volumes:
      - /data/minecraft_2023:/data
    environment:
      - TYPE=SPIGOT
      - VERSION=1.19.2
      - EULA=TRUE
      - SERVER_NAME=minecraft_2023_whitney
      - MODE=survival
      - SPAWN_PROTECTION=0
      - DIFFICULTY=hard
      - OPS=RicecakeSMS,pZ_aeriaL
      - ICON=https://i.imgur.com/sqjZGql.png
      - SEED="itsgoochfor2023"
      - MOTD="\u00A77Pinnerland, powered by \u00A75P\u00A79W\u00A75S\u00A77\!"
      - ALLOW_FLIGHT=false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minemap.rule=Host(`minemap.whitney.rip`)"
      - "traefik.http.routers.minemap.entrypoints=web"

##### OLD WORLD CONFIGS #####
#  minecraft_1.17:
#    image: itzg/minecraft-server:latest
#    container_name: minecraft_1.17_whitney
#    restart: always 
#    networks:
#      - minecraft_network
#    ports:
#      - "25565:25565"
#      - "9225:9225"
#    volumes:
#      - /data/minecraft_1.17:/data
#    environment:
#      - TYPE=SPIGOT
#      - EULA=TRUE
#      - SERVER_NAME=minecraft_1.17_whitney
#      - MODE=survival
#      - DIFFICULTY=hard
#      - OPS=RicecakeSMS
#      - ICON=https://i.imgur.com/sqjZGql.png
#      - SEED="-20020572336554879265524"
#      - MOTD="\u00A77Pinnerland 1.17, powered by \u00A75P\u00A79W\u00A75S\u00A77\!"
#      - ALLOW_FLIGHT=false
#
#  minecraft_1.16:
#    image: itzg/minecraft-server:java15
#    container_name: minecraft_1.16_whitney
#    restart: always 
#    networks:
#      - minecraft_network
#    ports:
#      - "25564:25565"
#      - "9224:9225"
#    volumes:
#      - /data/minecraft_1.16:/data
#    environment:
#      - TYPE=SPIGOT
#      - VERSION=1.16.5
#      - EULA=TRUE
#      - SERVER_NAME=minecraft_1.16_whitney
#      - MODE=spectator
#      - DIFFICULTY=hard
#      - OPS=RicecakeSMS
#      - ICON=https://i.imgur.com/sqjZGql.png
#      - ENABLE_COMMAND_BLOCK=true
#      - SEED=05181997
#      - MOTD="\u00A77Pinnerland 1.16, powered by \u00A75P\u00A79W\u00A75S\u00A77\!"
#      - ALLOW_FLIGHT=true

        
