version: "3"
services:
  minecraft:
    image: nimmis/spigot
    container_name: minecraft_whitney
    restart: always
    ports:
      - "25565:25565"
    volumes:
      - /data/minecraft:/minecraft
      - ./server.properties:/minecraft/server.properties
    environment:
      - EULA=true
      - MC_MAXMEM=2g
      - MC_MINMEM=512m
