global:
  scrape_interval:     15s
  external_labels:
    monitor: 'minecraft-monitor'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'minecraft_1.17'
    scrape_interval: 5s
    static_configs:
      - targets: ['minecraft_1.17_whitney:9225']
